services:
  - type: web
    name: learnsmart-platform
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 10000 